name: Build and test minimialf2py for windows on github actions

on: push

jobs:
  build-and-test:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: powershell
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7"]
        os: ["windows-latest"]
        include:
          - os: windows-latest
            environment-file: ci/requirements-windows.yml

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test_env
          python-version: ${{ matrix.python-version }}
          environment-file: ${{ matrix.environment-file }}
          miniforge-version: latest
          auto-update-conda: false
      - name: Build and install
        run: |
          python -m pip install -e . --no-deps -vv
      - name: Check out conda env details
        run: |
          conda info
          conda list
      - name: Import minimalf2py
        run: |
          python -c "import minimalf2py"
      - name: Run tests
        run: |
          pytest -v --pyargs minimalf2py.tests
